name: Package and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Build only (skip publish)'
        required: false
        default: 'false'
        type: choice
        options: ['false', 'true']

permissions:
  contents: read

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build wheel setuptools

      - name: Install runtime requirements
        if: hashFiles('requirements.txt') != ''
        run: |
          python -m pip install -r requirements.txt

      - name: Build sdist and wheel
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish distribution
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && inputs.dry_run == 'false')
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && inputs.dry_run == 'false')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      
